---
#
# Copyright 2021 Ramy ElEssawy
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
    - name: 1.1.1 (L1) Ensure 'Enforce password history' is set to '24 or more password(s)'
      win_security_policy:
        section: System Access
        key: PasswordHistorySize
        value: 24
    - name: 1.1.2 (L1) Ensure 'Maximum password age' is set to '60 or fewer days, but not 0'
      win_security_policy:
        section: System Access
        key: MaximumPasswordAge 
        value: 60        
    - name: 1.1.3 (L1) Ensure 'Minimum password age' is set to '1 or more day(s)'
      win_security_policy:
        section: System Access
        key: MinimumPasswordAge 
        value: 1 
    - name: 1.1.4 (L1) Ensure 'Minimum password length' is set to '14 or more character(s)'
      win_security_policy:
        section: System Access
        key: MinimumPasswordLength  
        value: 14
    - name: 1.1.5 (L1) Ensure 'Password must meet complexity requirements' is set to 'Enabled'
      win_security_policy:
        section: System Access
        key: PasswordComplexity  
        value: 1
    - name: 1.1.6 (L1) Ensure 'Store passwords using reversible encryption' is set to 'Disabled'
      win_security_policy:
        section: System Access
        key: ClearTextPassword  
        value: 0
    - name: 1.2.2 (L1) Ensure 'Account lockout threshold' is set to '10 or fewer invalid logon attempt(s), but not 0'
      win_security_policy:
        section: System Access
        key: LockoutBadCount  
        value: 10                                                                           
    - name: 1.2.3 (L1) Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)'
      win_security_policy:
        section: System Access
        key: ResetLockoutCount
        value: 15
    - name: 1.2.1 (L1) Ensure 'Account lockout duration' is set to '15 or more minute(s)'
      win_security_policy:
        section: System Access
        key: LockoutDuration
        value: 15